[package]
name = "bin"
version.workspace = true
edition.workspace = true

[dependencies]
bt = { path = "../bt" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
redb.workspace = true
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
clap = { version = "4.5.4", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.117"
upload-backend = { git = "https://github.com/Chikage0o0/upload-backend.git" }


snafu.workspace = true
reqwest = { version = "0.12.4" }
rss = "2.0.8"
scraper = "0.19.0"
chrono = "0.4.38"
bincode.workspace = true
config = "0.14.0"
url.workspace = true
