[workspace]
members = ["bin", "bt"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = "1"
librqbit = { version = "5" }
tokio = "1"
redb = "2"
url = "2"
snafu = "0"
bincode = "1"

[profile.release]
panic = "abort"   # Strip expensive panic clean-up logic
lto = "thin"      # Use Thin LTO for better compile times
strip = true      # Remove debug symbols
opt-level = "z"
codegen-units = 1
