[workspace]
members = ["bin", "bt", "subscribe"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
serde = "1"
librqbit = "5"
tokio = "1"
redb = "2"
url = "2"
snafu = "0"
bincode = "1"
