[package]
name = "subscribe"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = "0.12.4"
rss = "2.0.8"
scraper = "0.19.0"
snafu = "0.8.2"

[dev-dependencies]
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
